export const courses = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    shortDescription:
      "Master HTML, CSS, JavaScript, React, Node.js and more in this comprehensive course.",
    fullDescription:
      "This comprehensive bootcamp takes you from zero to full-stack developer. You'll learn HTML5, CSS3, JavaScript ES6+, React.js, Node.js, Express, MongoDB, and deployment. Includes 50+ real-world projects, coding challenges, and a capstone project. Perfect for beginners who want to launch a career in web development.",
    price: 89.99,
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop",
    instructor: "Sarah Mitchell",
    rating: 4.8,
    students: 12450,
    duration: "42 hours",
    level: "Beginner",
    specifications: [
      "50+ hands-on projects",
      "Lifetime access",
      "Certificate of completion",
      "Community support",
      "Job placement assistance",
    ],
  },
  {
    id: "2",
    title: "Advanced React & Next.js Masterclass",
    shortDescription:
      "Build production-ready applications with React 19, Next.js 15, and modern patterns.",
    fullDescription:
      "Dive deep into advanced React patterns, server components, Next.js App Router, authentication, database integration, and deployment strategies. This course covers everything from custom hooks and context to server actions, streaming, and edge computing. Build 5 production-grade applications.",
    price: 129.99,
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop",
    instructor: "James Rodriguez",
    rating: 4.9,
    students: 8320,
    duration: "38 hours",
    level: "Advanced",
    specifications: [
      "5 production-grade projects",
      "Server components deep dive",
      "Authentication patterns",
      "Database integration",
      "CI/CD pipeline setup",
    ],
  },
  {
    id: "3",
    title: "Python for Data Science & ML",
    shortDescription:
      "Learn Python, pandas, NumPy, scikit-learn, and TensorFlow for data science careers.",
    fullDescription:
      "Start your data science journey with Python. This course covers Python fundamentals, data manipulation with pandas, numerical computing with NumPy, data visualization with Matplotlib and Seaborn, machine learning with scikit-learn, and deep learning with TensorFlow. Work on real datasets from Kaggle competitions.",
    price: 94.99,
    category: "Data Science",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    instructor: "Dr. Emily Chen",
    rating: 4.7,
    students: 15800,
    duration: "55 hours",
    level: "Intermediate",
    specifications: [
      "Real Kaggle datasets",
      "10 ML projects",
      "TensorFlow deep dive",
      "Statistical analysis",
      "Career guidance",
    ],
  },
  {
    id: "4",
    title: "UI/UX Design Fundamentals",
    shortDescription:
      "Master design thinking, Figma, prototyping, and user research methodologies.",
    fullDescription:
      "Learn the complete UI/UX design process from user research to high-fidelity prototypes. This course covers design thinking methodology, wireframing, Figma mastery, component design systems, responsive design, accessibility, and usability testing. Build a professional portfolio with 6 case studies.",
    price: 74.99,
    category: "Design",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
    instructor: "Alex Thompson",
    rating: 4.6,
    students: 9200,
    duration: "28 hours",
    level: "Beginner",
    specifications: [
      "6 portfolio case studies",
      "Figma advanced techniques",
      "Design system creation",
      "User testing methods",
      "Industry mentorship",
    ],
  },
  {
    id: "5",
    title: "Cloud Architecture with AWS",
    shortDescription:
      "Design and deploy scalable cloud solutions using Amazon Web Services.",
    fullDescription:
      "Become a certified cloud architect with this comprehensive AWS course. Learn EC2, S3, Lambda, DynamoDB, CloudFormation, VPC networking, and more. Covers both Solutions Architect Associate and Professional certifications. Includes hands-on labs and real-world architecture scenarios from Fortune 500 companies.",
    price: 149.99,
    category: "Cloud Computing",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop",
    instructor: "Michael Park",
    rating: 4.8,
    students: 6700,
    duration: "45 hours",
    level: "Intermediate",
    specifications: [
      "AWS certification prep",
      "20+ hands-on labs",
      "Architecture case studies",
      "Cost optimization",
      "Security best practices",
    ],
  },
  {
    id: "6",
    title: "Mobile App Development with Flutter",
    shortDescription:
      "Build beautiful cross-platform mobile apps with Flutter and Dart from scratch.",
    fullDescription:
      "Learn to build stunning iOS and Android apps with a single codebase using Flutter. This course covers Dart programming, Flutter widgets, state management (Provider & Riverpod), Firebase integration, REST APIs, animations, and app store deployment. Build 4 complete apps including a social media clone.",
    price: 99.99,
    category: "Mobile Development",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop",
    instructor: "Priya Sharma",
    rating: 4.7,
    students: 11300,
    duration: "36 hours",
    level: "Beginner",
    specifications: [
      "4 complete apps",
      "State management mastery",
      "Firebase integration",
      "App store deployment",
      "Push notifications",
    ],
  },
  {
    id: "7",
    title: "Cybersecurity Essentials",
    shortDescription:
      "Learn ethical hacking, penetration testing, and security analysis techniques.",
    fullDescription:
      "Protect organizations from cyber threats with this hands-on cybersecurity course. Learn network security, ethical hacking, penetration testing with Kali Linux, vulnerability assessment, incident response, and compliance frameworks. Prepare for CompTIA Security+ and CEH certifications.",
    price: 119.99,
    category: "Cybersecurity",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    instructor: "David Kim",
    rating: 4.9,
    students: 5400,
    duration: "40 hours",
    level: "Intermediate",
    specifications: [
      "Kali Linux mastery",
      "Penetration testing labs",
      "Security+ cert prep",
      "Incident response",
      "Compliance frameworks",
    ],
  },
  {
    id: "8",
    title: "DevOps Engineering Complete Guide",
    shortDescription:
      "Master Docker, Kubernetes, CI/CD, Terraform, and modern DevOps practices.",
    fullDescription:
      "Transform your development workflow with DevOps engineering. This course covers Linux administration, Docker containerization, Kubernetes orchestration, CI/CD with GitHub Actions and Jenkins, Infrastructure as Code with Terraform, monitoring with Prometheus and Grafana, and GitOps workflows.",
    price: 134.99,
    category: "Cloud Computing",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&h=400&fit=crop",
    instructor: "Robert Wang",
    rating: 4.8,
    students: 7800,
    duration: "48 hours",
    level: "Advanced",
    specifications: [
      "Docker & Kubernetes",
      "CI/CD pipeline design",
      "Infrastructure as Code",
      "Monitoring & logging",
      "GitOps workflows",
    ],
  },
  {
    id: "9",
    title: "Digital Marketing Mastery",
    shortDescription:
      "Learn SEO, social media marketing, PPC advertising, and analytics for growth.",
    fullDescription:
      "Become a digital marketing expert with this comprehensive course. Master SEO techniques, Google Ads, Facebook & Instagram advertising, email marketing automation, content strategy, analytics with Google Analytics 4, and conversion rate optimization. Includes real campaign management experience.",
    price: 69.99,
    category: "Marketing",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    instructor: "Lisa Anderson",
    rating: 4.5,
    students: 18500,
    duration: "32 hours",
    level: "Beginner",
    specifications: [
      "Google Ads certification",
      "Social media strategy",
      "Email automation",
      "Analytics mastery",
      "Real campaign management",
    ],
  },
  {
    id: "10",
    title: "Blockchain & Web3 Development",
    shortDescription:
      "Build decentralized applications with Solidity, Ethereum, and smart contracts.",
    fullDescription:
      "Enter the world of Web3 development. Learn blockchain fundamentals, Solidity programming, smart contract development and testing, DeFi protocols, NFT marketplaces, and dApp deployment. Build 3 complete decentralized applications using Hardhat, Ethers.js, and React.",
    price: 139.99,
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=400&fit=crop",
    instructor: "Chris Nakamoto",
    rating: 4.6,
    students: 4200,
    duration: "35 hours",
    level: "Advanced",
    specifications: [
      "3 dApp projects",
      "Smart contract security",
      "DeFi protocol design",
      "NFT marketplace",
      "Testnet deployment",
    ],
  },
  {
    id: "11",
    title: "Machine Learning Engineering",
    shortDescription:
      "Deploy ML models to production with MLOps, APIs, and cloud infrastructure.",
    fullDescription:
      "Bridge the gap between data science and production engineering. Learn MLOps practices, model serving with FastAPI, containerized ML pipelines, A/B testing, feature stores, model monitoring, and cloud deployment on AWS SageMaker and Google Vertex AI. Covers the complete ML lifecycle.",
    price: 159.99,
    category: "Data Science",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
    instructor: "Dr. Alan Turing Jr.",
    rating: 4.9,
    students: 3600,
    duration: "50 hours",
    level: "Advanced",
    specifications: [
      "MLOps pipeline design",
      "Model serving & APIs",
      "A/B testing frameworks",
      "Cloud ML platforms",
      "Production monitoring",
    ],
  },
  {
    id: "12",
    title: "iOS Development with Swift",
    shortDescription:
      "Create stunning iOS applications using Swift, SwiftUI, and Apple frameworks.",
    fullDescription:
      "Master iOS development from the ground up. Learn Swift programming, SwiftUI for modern interfaces, UIKit for complex layouts, Core Data for persistence, networking, push notifications, and App Store submission. Build 5 apps including a fitness tracker and recipe app.",
    price: 109.99,
    category: "Mobile Development",
    image: "https://images.unsplash.com/photo-1621839673705-6617adf9e890?w=600&h=400&fit=crop",
    instructor: "Jennifer Lee",
    rating: 4.7,
    students: 6100,
    duration: "40 hours",
    level: "Intermediate",
    specifications: [
      "5 complete iOS apps",
      "SwiftUI & UIKit",
      "Core Data mastery",
      "App Store deployment",
      "In-app purchases",
    ],
  },
];

export const categories = [
  "All",
  "Web Development",
  "Data Science",
  "Design",
  "Cloud Computing",
  "Mobile Development",
  "Cybersecurity",
  "Marketing",
];

export const testimonials = [
  {
    id: 1,
    name: "Amanda Foster",
    role: "Frontend Developer at Google",
    avatar: "AF",
    text: "SkillForge completely transformed my career. The web development bootcamp gave me the skills and confidence to land my dream job. The projects were incredibly practical and the community support was amazing.",
    rating: 5,
  },
  {
    id: 2,
    name: "Daniel Martinez",
    role: "Data Scientist at Netflix",
    avatar: "DM",
    text: "The data science course was exactly what I needed. The curriculum was up-to-date with industry standards, and the hands-on Kaggle projects prepared me for real-world challenges. Highly recommended!",
    rating: 5,
  },
  {
    id: 3,
    name: "Sophie Williams",
    role: "UX Designer at Spotify",
    avatar: "SW",
    text: "As someone switching careers from teaching, SkillForge made the transition seamless. The UI/UX course was thorough, the mentorship incredible, and I built a portfolio that got me hired within 3 months.",
    rating: 5,
  },
];
